{{ config(materialized='view') }}

SELECT
  PARTY_ID,
  SOURCE_PARTY_CODE,
  PARTY_NAME,
  SOURCE_SYSTEM_IDENTIFIER,
  RDH_INSERT_TIMESTAMP,
  LAG(RDH_INSERT_TIMESTAMP, 1, '9999-12-31 23:59:59') OVER (PARTITION BY PARTY_ID ORDER BY RDH_INSERT_TIMESTAMP DESC) AS RDH_CLOSURE_TIMESTAMP
FROM
   {{ ref("T_DDS_PARTY")}} 
ORDER BY
  party_id ASC,
  RDH_INSERT_TIMESTAMP DESC