  {{ config(
      materialized='table' 
  ) }}

  ---- CREATING THE BASE QUERY TO EXTRACT DATA FROM DRIVING TABLES , PICKING ALL THE ACTIVE RECORDS ----

WITH PARTYCMD AS 
(

SELECT
  CAST(ENTITY_ID AS STRING) AS SOURCE_PARTY_CODE,--UPDATE THE LENGTH TO 250
  SUBSTR(TRIM(ENTITY_LEGAL_NAME),1,160) AS SOURCE_PARTY_NAME
FROM
  {{source('test_01','cmdt_customer_full')}} CMDT_CUST_FULL
WHERE
  CMDT_CUST_FULL.HDS_END_DATE = PARSE_DATE('%F','3500-12-31')
)
/*UNION ALL

SELECT
  DISTINCT(CAST(GROUP_CMD_ID AS STRING)) AS SOURCE_PARTY_CODE,--UPDATE THE LENGTH TO 250
  SUBSTR(IFNULL(GROUP_NAME,'UNKNOWN'),1,160) AS SOURCE_PARTY_NAME
FROM
  {{source('test_01','dmdt_cmd_dmd_wdw_grouping')}} DMDT_WDW_GROUP
WHERE
  DMDT_WDW_GROUP.HDS_END_DATE = PARSE_DATE('%F','3500-12-31')

UNION ALL

SELECT
  DISTINCT(CAST(DMDT_CLI_SA.ATTRIBUTE_VALUE AS STRING)) AS SOURCE_PARTY_CODE,--UPDATE THE LENGTH TO 250
  SUBSTR(IFNULL(DMDT_CLI_SA.ATTRIBUTE_VALUE,'UNKNOWN'),1,160) AS SOURCE_PARTY_NAME
FROM
  {{source('test_01','dmdt_cmd_dmd_wdw_client_sa')}} DMDT_CLI_SA
INNER JOIN
  {{source('test_01','dmdt_cmd_dmd_wdw_sa')}} DMDT_SA
ON
  DMDT_CLI_SA.ATTRIBUTE_CMD_ID=DMDT_SA.ATTRIBUTE_CMD_ID
WHERE
  DMDT_CLI_SA.HDS_END_DATE = PARSE_DATE('%F','3500-12-31')
  AND DMDT_SA.HDS_END_DATE = PARSE_DATE('%F','3500-12-31')
)

*/

  SELECT

    CONCAT('CMD',SOURCE_PARTY_CODE) AS PARTY_ID,
    SOURCE_PARTY_CODE,
    SOURCE_PARTY_NAME,
    'CMD' AS SOURCE_SYSTEM_IDENTIFIER
    FROM PARTYCMD

